### ISSUE TITLE
Generating definitions throws an error

### ISSUE THREAD

**Issue by Vehmloewff** [fabiospampinato/plain-object-is-equal#1]
When I run `npm run compile` and then open `dist/index.d.ts`, I get the following error in my IDE (VS Code) on line 6:

```
'isEqual' refers to a value, but is being used as a type here.
```

I believe that this has something to do with [typescript-transform-export-interop](https://github.com/fabiospampinato/typescript-transform-export-interop).

**Comment by fabiospampinato** [comment]
Yeah I use `"skipLibCheck": true` so I don't see these useless errors. This is most probably related to [typescript-transform-export-interop](https://github.com/fabiospampinato/typescript-transform-export-interop), if you know of a way to fix this PRs are welcome 👍
